Repository jaejin9771/Webmail-System, pull requests merged in 2025-05, with the labels that each got.

#6 UserAdminService 수정(#5)
  src/main/java/deu/cse/spring_webmail/control/AdminController.java
  src/main/java/deu/cse/spring_webmail/service/UserAdminService.java
  src/main/resources/application.properties
  src/main/webapp/WEB-INF/views/admin/add_user.jsp
  src/main/webapp/WEB-INF/views/admin/admin_menu.jsp
  src/main/webapp/WEB-INF/views/admin/delete_user.jsp
Labels: 배재진, 박세준

#7 feat:James 3.8.2 사용자 추가 기능 구현(#5)
  src/main/java/deu/cse/spring_webmail/control/AdminController.java
  src/main/java/deu/cse/spring_webmail/control/AuthController.java
  src/main/java/deu/cse/spring_webmail/service/UserAdminService.java
  src/main/webapp/WEB-INF/views/admin/add_user.jsp
Labels: 배재진

#8 feat:James3.8.2 적용 후 사용자 관리 기능 전체 수정(#5)
  src/main/java/deu/cse/spring_webmail/control/AdminController.java
  src/main/java/deu/cse/spring_webmail/model/UserAdminAgent.java
  src/main/java/deu/cse/spring_webmail/service/UserAdminService.java
  src/main/webapp/WEB-INF/views/admin/admin_menu.jsp
  src/main/webapp/WEB-INF/views/admin/delete_user.jsp
  src/main/webapp/WEB-INF/views/admin/sidebar_admin_menu.jsp
Labels: 배재진

#10 JaCoCo, Junit5 의존성 추가(#9)
  pom.xml
Labels: 배재진

#12 feat:메일리스트 페이지별로 표시(#11)
  src/main/java/deu/cse/spring_webmail/control/AuthController.java
  src/main/java/deu/cse/spring_webmail/model/MessageFormatter.java
  src/main/java/deu/cse/spring_webmail/model/Pop3Agent.java
  src/main/java/deu/cse/spring_webmail/service/MailService.java
  src/main/webapp/WEB-INF/views/main_menu.jsp
Labels: 박세준

#16 feat: 메일 검색, 삭제 시 확인 기능(#11)
  src/main/java/deu/cse/spring_webmail/control/AuthController.java
  src/main/java/deu/cse/spring_webmail/model/MessageFormatter.java
  src/main/java/deu/cse/spring_webmail/model/Pop3Agent.java
  src/main/webapp/WEB-INF/views/main_menu.jsp
Labels: 박세준

#18 UserAdminService 클래스 리팩토링(#17)
  src/main/java/deu/cse/spring_webmail/service/UserAdminService.java
Labels: 배재진

#23 feat:UserAdminServiceTest 작성 및 AppConfig 클래스 추가(#22)
  src/main/java/deu/cse/spring_webmail/AppConfig.java
  src/main/java/deu/cse/spring_webmail/service/UserAdminService.java
  src/test/java/deu/cse/spring_webmail/service/UserAdminServiceTest.java
Labels: 배재진

#25 feat: Spring Security 적용 및 일부 코드 수정(#24)
  pom.xml
  src/main/java/deu/cse/spring_webmail/config/JamesAuthenticationProvider.java
  src/main/java/deu/cse/spring_webmail/config/RoleBasedSuccessHandler.java
  src/main/java/deu/cse/spring_webmail/config/SpringSecurityConfig.java
  src/main/java/deu/cse/spring_webmail/control/AuthController.java
  src/main/java/deu/cse/spring_webmail/control/ReadController.java
  src/main/java/deu/cse/spring_webmail/control/SentMailController.java
  src/main/java/deu/cse/spring_webmail/control/WriteController.java
  src/main/webapp/WEB-INF/views/admin/sidebar_admin_menu.jsp
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/WEB-INF/views/main_menu.jsp
  src/main/webapp/WEB-INF/views/read_mail/sidebar_read_menu.jsp
  src/main/webapp/WEB-INF/views/sent_mail/slidebar_sent_menu.jsp
  src/main/webapp/WEB-INF/views/sidebar_menu.jsp
  src/main/webapp/WEB-INF/views/sidebar_previous_menu.jsp
Labels: 배재진

#29 AuthController 코드스멜 수정
  src/main/java/deu/cse/spring_webmail/control/AuthController.java
Labels: 배재진

#40 AdminControllerTest 작성
  src/main/java/deu/cse/spring_webmail/repository/AddressBookRepository.java
  src/test/java/deu/cse/spring_webmail/control/AdminControllerTest.java
Labels: 배재진
